title:            Gochxx Blog
author:           Gochxx
description:      "Gochx Blog (Theme ist Jekyll site with the GitBook style)."
version:          1.0
gitbook_version:  3.2.3
url:              'https://gochxx.github.io/blog/'
remote_theme:     sighingnow/jekyll-gitbook


nav:
  - title: "Home"
    url: /
  - title: "pages"
    url: /_pages/
  - title: "posts"
    url: /_posts/

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Blog"
    url: /blog/
  - title: "Kontakt"
    url: /contact/

toc:
    enabled: true
    h_min: 1
    h_max: 3

ordered_collections:
  - posts
  - pages
